#!/bin/sh

blockMesh
N_PROCS=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
[ -z "$N_PROCS" ] && N_PROCS=4 # if N_PROCS not found, set it to 4
sed -i "s/numberOfSubdomains .*/numberOfSubdomains $N_PROCS;/g" system/decomposeParDict

rm -rf 0
cp -r 0.orig 0

decomposePar -force > log.decompose
mpirun -np $N_PROCS foamRun -solver multicomponentFluid -parallel > log.foamRun
