#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#wclean all

# Compile OpenFOAM_Aalto libraries
src/Allwmake $targetType $*

cd unittests
#wclean
wmake
cd ..

cd benchmarks/serial
#wclean
wmake

cd ../parallel
#wclean
wmake
