#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

rm -rf $FOAM_USER_LIBBIN/libchemistryModel_DLB.so
rm -rf $FOAM_USER_LIBBIN/libODE_DLB.so
unlink $FOAM_USER_LIBBIN/libc_pyjac_test.so
rm -rf $FOAM_USER_LIBBIN/unittests/pyjacTestMech/build

pushd src > /dev/null
    wclean all
popd > /dev/null

wclean tests/unittests

wclean tests/validation/pyjacTests/PSRTest


