#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

PLATFORM=NOT_DEFINED #PUHTI / DESKTOP / TAITO
CLEAN_ALL=false

POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --clean)
        CLEAN_ALL=true
        shift # past argument
        ;;
        --platform)
        PLATFORM="$2"
        shift # past argument
        shift # past value
        ;;
        *) 
        echo "Error: Correct platform syntax ./Allwmake --platform PUHTI/MAHTI/DESKTOP" 
        exit 1 
        ;;    
    esac

done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ $CLEAN_ALL == true ]; then
    ./Allwclean
fi

if [ $PLATFORM == PUHTI ]; then
    . /appl/soft/eng/OpenFOAM/OpenFOAM-8_intelmpi/etc/bashrc
    module load intel-mkl
    cp  src/ODE_DLB/Make/options.puhti src/ODE_DLB/Make/options
elif [ $PLATFORM == MAHTI ]; then
    . /appl/soft/eng/OpenFOAM/OpenFOAM-8/etc/bashrc
    module load  openblas
    cp  src/ODE_DLB/Make/options.mahti src/ODE_DLB/Make/options
elif [ $PLATFORM == DESKTOP ]; then
    cp  src/ODE_DLB/Make/options.desktop src/ODE_DLB/Make/options
else
    echo Error: Correct platform syntax ./Allwmake --platform  DESKTOP/PUHTI/MAHTI
    exit 1
fi


cp -r pyJac $WM_PROJECT_USER_DIR/
cd src/thermophysicalModels/chemistryModel
wmake libso
cd ../../ODE_DLB
wmake libso
cd ../../

cd ./unittests
wmake
./test.sh
cd ../

cd applications/
./Allwmake --clean
