#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

CLEAN_ALL=false

POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --clean)
        CLEAN_ALL=true
        shift # past argument
        ;;
        *) 
        exit 1 
        ;;    
    esac

done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ $CLEAN_ALL == true ]; then
    ./Allwclean
fi

cd solvers/
wmake chemFoam_timed
wmake reactingFoam_timed
wmake sprayFoam_timed
cd ../
