#!/bin/bash

while getopts m: flag
do
    case "${flag}" in
        m) mechname=${OPTARG};;
    esac
done

echo "Compiling mechanism: $mechname...";

[[ -d mechanisms/$mechname/lib/build ]] && rm -r mechanisms/$mechname/lib/build
cp -r mechanisms/$mechname/lib/src .
./runCmake.sh
mv build mechanisms/$mechname/lib/
rm -rf src

echo "Compiled!"
echo "Compiled $mechname mechanism location: mechanisms/$mechname/lib/build/libc_pyjac.so";
