#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"


runApplication foamMergeCase ../shearlayer_DLB
cp -r ../shearlayer_DLB/0.orig .


#!/bin/sh
# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

cd pyJac/lib
./runCmake.sh
cd -
cp -r pyJac/foam constant/
cp pyJac/lib/build/libc_pyjac.so constant/foam/

runApplication blockMesh

N_PROCS=$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
[ -z "$N_PROCS" ] && N_PROCS=4 # if N_PROCS not found, set it to 4

foamDictionary system/decomposeParDict -entry numberOfSubdomains -set $N_PROCS

cp -r 0.orig 0

runApplication decomposePar
runParallel "$(getApplication)"
