#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0 chemFoam.out  \
   validation/OF_pyJac_vs_CHEMKINII.eps

#------------------------------------------------------------------------------
