#!/bin/bash

# Copy tutorial files from OpenFOAM
cp -nr $WM_PROJECT_DIR/test/chemistry/gri/* .

# Compile and copy mechanism
cd pyJac/lib
./runCmake.sh
cd -
cp -r pyJac/foam constant/
cp pyJac/lib/build/libc_pyjac.so constant/foam/

# Set DLB dictionaries
foamDictionary -entry loadbalancing -set {} constant/chemistryProperties
foamDictionary -entry loadbalancing/active -add false constant/chemistryProperties
foamDictionary -entry refmapping -set {} constant/chemistryProperties
foamDictionary -entry refmapping/active -add false constant/chemistryProperties

# Set pyJac and LAPACK
foamDictionary  constant/chemistryProperties -entry type -add loadBalanced_pyJac
foamDictionary -entry ode/solver -set seulex_LAPACK constant/chemistryProperties

# Include libraries
foamDictionary -entry libs -set '("libchemistryModel_DLB.so" "libODE_DLB.so" "$FOAM_CASE/constant/foam/libc_pyjac.so")' system/controlDict

# Change links to mechanism files
sed -i 's|#include .*|#include "$FOAM_CASE/constant/foam/reactions.foam"|g' constant/chemistryProperties
sed -i 's|#include .*|#include "$FOAM_CASE/constant/foam/species.foam"\n#include "$FOAM_CASE/constant/foam/thermo.foam"|g' constant/physicalProperties

# Run chemFoam
chemFoam > log.chemFoam

# Run validation
(cd validation && ./Allrun $*)
