#!/bin/bash

while getopts m: flag
do
    case "${flag}" in
        m) mechname=${OPTARG};;
    esac
done
echo "COMPILED MECHANISM: $mechname";

rm -rf out/ build/ fit_validation_figs/ foam_mech_files/

mkdir foam_mech_files
python -m pyjac --lang c --last_species N2 --input mechanisms/$mechname/chem.cti

sed -i '4 a int PYJAC_NSP();\nint PYJAC_FWD_RATES();' out/chem_utils.h
sed -i '3 a int PYJAC_NSP()\n{\n    return NSP;\n}\nint PYJAC_FWD_RATES()\n{\n    return FWD_RATES;\n}' out/chem_utils.c

./runCmake.sh
mv build/libc_pyjac.so foam_mech_files/
./makeMechFileForOF.sh
python3 thermoFitter/fit_thermoProps.py --mechanism $mechname

rm -rf out/ build/ fit_validation_figs/
